//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamaWebApp.TamaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TamaService.ITamaLogic")]
    public interface ITamaLogic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamaLogic/GetTamagotchi", ReplyAction="http://tempuri.org/ITamaLogic/GetTamagotchiResponse")]
        string GetTamagotchi(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamaLogic/GetTamagotchi", ReplyAction="http://tempuri.org/ITamaLogic/GetTamagotchiResponse")]
        System.Threading.Tasks.Task<string> GetTamagotchiAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamaLogic/AddTamagotchi", ReplyAction="http://tempuri.org/ITamaLogic/AddTamagotchiResponse")]
        void AddTamagotchi(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITamaLogic/AddTamagotchi", ReplyAction="http://tempuri.org/ITamaLogic/AddTamagotchiResponse")]
        System.Threading.Tasks.Task AddTamagotchiAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITamaLogicChannel : TamaWebApp.TamaService.ITamaLogic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamaLogicClient : System.ServiceModel.ClientBase<TamaWebApp.TamaService.ITamaLogic>, TamaWebApp.TamaService.ITamaLogic {
        
        public TamaLogicClient() {
        }
        
        public TamaLogicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamaLogicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamaLogicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamaLogicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTamagotchi(int value) {
            return base.Channel.GetTamagotchi(value);
        }
        
        public System.Threading.Tasks.Task<string> GetTamagotchiAsync(int value) {
            return base.Channel.GetTamagotchiAsync(value);
        }
        
        public void AddTamagotchi(string name) {
            base.Channel.AddTamagotchi(name);
        }
        
        public System.Threading.Tasks.Task AddTamagotchiAsync(string name) {
            return base.Channel.AddTamagotchiAsync(name);
        }
    }
}
